# Generated by Django 6.0.7 on 2026-07-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='ultima_respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='ultimo_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
